spring:
  data:
    mongodb:
      username: dhia
      password: dhia
      host: localhost
      port: 27017
      authentication-database: admin
      database: notification
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages : '*'
        spring.json.type.mapping: orderConfirmation:com.dhia.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.dhia.ecommerce.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: dhia
    password: dhia
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
server:
  port: 8040